debug: true

logging:
 level:
  org:
   springframework:
    boot:
     autoconfigure: ERROR
jwt:
 secret: javainuse
 
spring:
 datasource:
  url: jdbc:mysql://localhost/jwttoken?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&serverTimezone=Asia/Karachi
  username: root
  password: root
  platform: mysql
 
 jpa:
    hibernate:
      ddl-auto: create-drop
 
springfox.documentation.swagger.v2.path: /docs

swagger:
  enabled: true 
  
api:
  title: OPEN CONNECT API
  description: REST Services for interacting with the exchange
  version: 1.0
  contact: 033333333
  name: Paysys Labs
  link: http://www.paysyslabs.com/
  email: info@paysyslabs.com